<a href="https://colab.research.google.com/github/JungAh12/Everyone_TF2.0/blob/master/TF2_0_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q tensorflow-gpu==2.0.0-rc1
import tensorflow as tf

     |████████████████████████████████| 380.5MB 46kB/s 
     |████████████████████████████████| 4.3MB 45.0MB/s 
     |████████████████████████████████| 501kB 70.9MB/s 


#layer
tensorflow는 keras의 모든 API를 tf.keras에 포함하고 있다.

In [0]:
#대부분의 레이어는 첫번째 인수가 output dim 또는 channel이다.
layer = tf.keras.layers.Dense(100) #Dense==FullyConnected

#input dim은 처음 실행 시 유추할 수 있어서 종종 불필요하다.
#일부 모델에서는 수동으로 input dim 써주는게 유용할 수 있다.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [3]:
#층을 사용하는 것은 호출하면된다.
layer(tf.zeros([10,5])) #10x5

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
#layer 안에 있는 변수확인하기
print(layer.variables) # 층안에 있는 모든 변수 확인가능
print(layer.trainable_variables) # 학습 가능한 변수 확인가능

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.22709674,  0.25902545, -0.5331796 , -0.37266076, -0.4702699 ,
         0.37390703,  0.6028841 , -0.04740435, -0.5029723 ,  0.1985023 ],
       [ 0.01715243,  0.07172394,  0.50818235,  0.01662874, -0.17842638,
         0.40023583, -0.48210758, -0.40912744,  0.06295311,  0.22801131],
       [-0.15682885,  0.11161578, -0.16400927,  0.20083141, -0.03044224,
        -0.6296113 ,  0.58754295,  0.11028928,  0.48258895,  0.5174548 ],
       [-0.23493868, -0.38838416,  0.09327531,  0.05146134, -0.4243813 ,
        -0.19744873, -0.23812622, -0.2625494 , -0.46005678, -0.13139057],
       [ 0.03414893, -0.37218758, -0.060664  , -0.3923784 ,  0.21773201,
        -0.38512576,  0.13944906, -0.0731445 ,  0.46893448,  0.62344176]],
      dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]
[<tf.Variable 'dense_1/kernel:0' shape=(5, 1

In [6]:
#kernel은 weight, bias는 bias이다.
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.22709674,  0.25902545, -0.5331796 , -0.37266076, -0.4702699 ,
          0.37390703,  0.6028841 , -0.04740435, -0.5029723 ,  0.1985023 ],
        [ 0.01715243,  0.07172394,  0.50818235,  0.01662874, -0.17842638,
          0.40023583, -0.48210758, -0.40912744,  0.06295311,  0.22801131],
        [-0.15682885,  0.11161578, -0.16400927,  0.20083141, -0.03044224,
         -0.6296113 ,  0.58754295,  0.11028928,  0.48258895,  0.5174548 ],
        [-0.23493868, -0.38838416,  0.09327531,  0.05146134, -0.4243813 ,
         -0.19744873, -0.23812622, -0.2625494 , -0.46005678, -0.13139057],
        [ 0.03414893, -0.37218758, -0.060664  , -0.3923784 ,  0.21773201,
         -0.38512576,  0.13944906, -0.0731445 ,  0.46893448,  0.62344176]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

#사용자 정의 층 구현
`tf.keras.Layer`클래스를 상속해서 구현한다.

* `__init__`에서 층에 필요한 파라미터를 입력받는다.

* `build`에서 입력 텐서의 크기를 얻고 초기화를 진행할 수 있다.

* `call`에서 forward computation을 진행할 수 있다.

꼭 `build`를 호출해서 변수를 생성하지 않아도 된다. `__init__`에서 생성할 수 있다.

**하지만 `build`에서 변수를 생성하면 층이 작동할 입력 크기를 기준으로 나중에 변수를 만들 수 있다. 그러나 `__init__`에서 변수를 생성하면 변수 생성에 필요한 크기를 명시적으로 지정해줘야한다.**

In [7]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs  #num_outputs 변수 생성

    def build(self, input_shape):
        self.kernel = self.add_variable("kernel",
                                        shape=[int(input_shape[-1]),    #weight의 크기는 입력 데이터의 끝 shape x num_outpus이다.
                                               self.num_outputs])
        def call(self, input):
            return tf.matmul(input, self.kernel)    #input과 weight 곱연산.

layer = MyDenseLayer(10)    #num_outputs = 10
print(layer(tf.zeros([10,5])))  #input data = 0으로 채워진 10x5 tensor
print(layer.trainable_variables)    #학습 가능한 변수 출력

Instructions for updating:
Please use `layer.add_weight` method instead.
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(10, 5), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.299897  , -0.00206733, -0.19329375,  0.60096234,  0.01382393,
        -0.2837903 , -0.4636522 ,  0.02921677,  0.37188286, -0.59630984],
       [ 0.50419   , -0.38440707, -0.31616986, -0.54895496,  0.5190546 ,
        -0.03576207, -0.41125026,  0.24548757,  0.22366327, -0.21665746],
       [-0.3027421 , -0.4285788 ,  0.1073637 ,  0.05980027,  0.34783858,
        -0.06087887, -0.62249744,  0.09057784, -0.09778166, -0.50190574],
       [ 0.4341703 ,  0.5131001 , -0.26609898, -0.59436315,  0.4570374 ,
        -0.5228158 ,  0.49676615, -0.38585663,  0.30197138, -0.5593768 ],
       [-0.00742728,  0.11443192,  0.021

#Model : layer 구성하기
모델은 기존 layer들을 조합해서 구현된다.

다른 층을 포함한 모델을 만들기 위해서 사용하는 메인 클래스는 `tf.keras.Model`이다.

In [9]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters

        self.conv2a = tf.keras.layers.Conv2D(filters1,(1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()

        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()

        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()

    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training=training)

        x += input_tensor
        return tf.nn.relu(x)

block = ResnetIdentityBlock(1, [1,2,3]) # kernel_size = 1, filters = [1,2,3]
print(block(tf.zeros([1,2,3,3]))) # 0으로 채워진 1x2x3x3 tensor 입력
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_1/conv2d_3/kernel:0', 'resnet_identity_block_1/conv2d_3/bias:0', 'resnet_identity_block_1/batch_normalization_3/gamma:0', 'resnet_identity_block_1/batch_normalization_3/beta:0', 'resnet_identity_block_1/conv2d_4/kernel:0', 'resnet_identity_block_1/conv2d_4/bias:0', 'resnet_identity_block_1/batch_normalization_4/gamma:0', 'resnet_identity_block_1/batch_normalization_4/beta:0', 'resnet_identity_block_1/conv2d_5/kernel:0', 'resnet_identity_block_1/conv2d_5/bias:0', 'resnet_identity_block_1/batch_normalization_5/gamma:0', 'resnet_identity_block_1/batch_normalization_5/beta:0']


In [10]:
#대부분은 다음과 같이 구현해서 사용한다.
model = tf.keras.Sequential([
                             tf.keras.layers.Conv2D(1, (1,1), input_shape=(None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1, padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1,1)),
                             tf.keras.layers.BatchNormalization()
])

model(tf.zeros([1,2,3,3]))

<tf.Tensor: id=990, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>